### ISSUE TITLE
Tuning label is reversed

### ISSUE THREAD

**Issue by krispenney** [airhorns/extractab#1]
:wave:, really cool project!

Currently the tuning label is expressed from high-low strings, where it would conventionally be low-high. So for the below example: `AECGDA` -> `ADGCEA` (Standard tuning, capo 5).

<img width="832" alt="screen shot 2018-04-13 at 9 37 15 am" src="https://user-images.githubusercontent.com/1909544/38737812-625397b8-3efe-11e8-9c48-150a18f0feec.png">

Should just need a `.reverse()` [on this method](https://github.com/airhorns/extractab/blob/master/app/javascript/music/guitar_tuning.ts#L21)!

**Comment by airhorns** [comment]
Whoopsiedasies! Thanks @krispenney !
